export default /* @html */`
<iron-ajax
    id="ajax_menu"
    handle-as="json"
    rejectWithRequest
    debounce-duration="300">
</iron-ajax>
<iron-ajax
    id="ajax_descendents"
    handle-as="json"
    rejectWithRequest
    debounce-duration="300">
</iron-ajax>
<iron-ajax
    id="ajax_page"
    handle-as="json"
    rejectWithRequest
    debounce-duration="300">
</iron-ajax>
`
